### ISSUE TITLE
Out of sync with gorm.io/driver/sqlite

### ISSUE THREAD

**Issue by samuelncui** [glebarez/sqlite#104]
I have currently added some changes in `migrator.go` on gorm.io/driver/sqlite, which can resolve some problems in the issues. Could you rebase those changes? Thx.

**Comment by glebarez** [comment]
Hello @samuelncui  thank you for the message.
Unfortunately I am super busy right now, but will be glad to merge your contributions, and even welcome you as a co-author, if you wish.

Just a quick note: the upstream sync for this repo is usually a merge-type work, because rebase would reassign tags to different commits, resulting in golang package manager checksum failures.

**Comment by glebarez** [comment]
Synced with upstream.
